cache:
  refresh:
    cronErrorCode: 0 0 1 * * SUN # every day at 1 AM
    accounts: 0 */5 * * * * # every 5 minutes
  user:
    cleanup:
      rate: 43200000 # 12 hours

management:
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) %clr([%X{traceId}]){yellow} %clr(%logger{36}){cyan} - %msg%n'

security:
  cvv-encryption:
    secret-key: ${SECURITY_CVV_ENCRYPTION_SECRET_KEY}
  encryption:
    secret-key: ${SECURITY_ENCRYPTION_SECRET_KEY}

spring:
  application:
    name: account-service
  data:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    redis:
      host: ${REDIS_HOST}
      port: 6379
  main:
    banner-mode: off
server:
  port: 8084


feign:
  client:
    email-service:
      url: ${EMAIL_SERVICE_URL}/api/v1/email
      verifyUser: /user/verify
      passwordReset: /user/password-reset
      cardApprove: /card/approval
      cardPending: /card/pending
      cardReject: /card/rejection
    parameter-service:
      url: ${PARAMETER_SERVICE_URL}/api/v1
      getByCode: /error-codes/error-code
      logError: /log/error
      getAllErrorCodes: /error-codes/error-code/all